"""initial db migrate

Revision ID: d1e8d5d82564
Revises: 
Create Date: 2024-03-07 15:23:01.462421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1e8d5d82564'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('history')
    #op.drop_index('name', table_name='accounts')
    #op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('stage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_contacted', mysql.DATETIME(), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], name='accounts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'accounts', ['name'], unique=True)
    op.create_table('history',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('orig_text', mysql.TEXT(), nullable=True),
    sa.Column('datetime', mysql.DATETIME(), nullable=True),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('action', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='history_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
